### ISSUE TITLE
Error at getting repositorys

### ISSUE THREAD

**Issue by Motytheultimate** [Bogdan-Lyashenko/codecrumbs#15] opened 2019-02-13 19:17 UTC
Looks like the path issue is fixed.

but now it throws an error at the dependecies option:

uncaught at reactByUpdatingFoldersState TypeError: Cannot read property 'dependencies' of undefined

on [Tree.js](https://github.com/Bogdan-Lyashenko/codecrumbs/blob/master/src/public/js/components/treeDiagram/component/Tree/Source/Tree.js#L135)

`   {dependenciesDiagramOn &&
        selectedNode.dependencies && (
          <DependenciesTree
            namespace={namespace}`

_Originally posted by @Motytheultimate in https://github.com/Bogdan-Lyashenko/codecrumbs/issues/14#issuecomment-463325932_

**Comment by Bogdan-Lyashenko** [comment] 2019-02-13 20:02
Hi 🙂 Did you select another node from diagram or just ran codecrumbs and it fails right away? If you just ran it without interaction - `selectedNode` will refer to `entry point`, so maybe there is still an issue. But it's super hard to imagine what is going without knowing what code you run, since, since "it works on my computer" 😄 Can you please try this https://github.com/lucasbento/react-redux-todo (just clone that repo, like it's your codebase) and run codecrumbs for it (same way as you doing it right now for your project). Let's if it works, because it worked perfectly fine for me when I tested it on windows. Thanks a lot 👍

**Comment by Motytheultimate** [comment] 2019-02-13 20:24
I ran the Project and it worked the 

I use a modified version of [this](https://github.com/wbkd/webpack-starter)

**Comment by Bogdan-Lyashenko** [comment] 2019-02-13 20:43
Ok, thanks for the link, I will run that project and see if I reproduce the issue.

**Comment by Motytheultimate** [comment] 2019-02-13 20:44
I cloned a clean version of it and it runs 
thats strange i ll try to figure it out.

maybe there is a dependency thats breaking it?

**Comment by Bogdan-Lyashenko** [comment] 2019-02-13 20:54
No, it should be fine with dependencies, if it fails - dependencies array just should be empty. Can you try to run with “-f true” extra param (fallback for ast parser), also, can you try to use another entry point? (it doesn’t really matter what file is set there)

**Comment by Motytheultimate** [comment] 2019-02-13 21:33
I found my issue it was the run command
i changed from 
    "cc": "codecrumbs -d src -e **./**src/scripts/index.js"
to 
    "cc": "codecrumbs -d src -e src/scripts/index.js"
and it works

**Comment by Motytheultimate** [comment] 2019-02-13 21:37
thank you for your help 👍 

but the issue was on my side 🤦

**Comment by Bogdan-Lyashenko** [comment] 2019-02-13 21:46
Hm, interesting.. yeah, makes sense, but still quite inconvenient) will see if I can fix it easily  to resolve to correct file even when it starts from ./
Thanks :)

**Comment by Motytheultimate** [comment] 2019-02-13 21:50
Just a quick question while i am at it 
![image](https://user-images.githubusercontent.com/5394111/52746338-96766780-2fe1-11e9-9179-7fd6bee5918e.png)

thats a dependency right?
or what dependency shows on the sidebar?

**Comment by Bogdan-Lyashenko** [comment] 2019-02-14 21:13
Yes, this is a dependency (and you selected connection), so when it’s selected, the code of two files (what imports and from where imorted) will be highlighted in in sidebar

**Comment by Bogdan-Lyashenko** [comment] 2019-02-14 21:13
I am gonna add all info to Readme :)

**Comment by Motytheultimate** [comment] 2019-02-15 05:09
So basically its not expected to look like this?
![image](https://user-images.githubusercontent.com/5394111/52835797-4d5d0b00-30e8-11e9-93b6-4f5fdebabaef.png)

**Comment by Bogdan-Lyashenko** [comment] 2019-02-15 06:27
Oh.. cmon..)) yeah, you found another bug probably.. it should show two files there. Damn it) Alright, I didn’t check that on windows, can be part of “paths issues” as well. Will try to fix today. Thanks ;)

**Comment by Bogdan-Lyashenko** [comment] 2019-02-15 06:30
Is it like that always or for some selections?

**Comment by Motytheultimate** [comment] 2019-02-15 06:34
I haven't played around with it that much yet but I yesterday i couldn't get anything to show on the dependency tab

**Comment by Bogdan-Lyashenko** [comment] 2019-02-15 07:15
I see, must be something simple then, thanks.

**Comment by Bogdan-Lyashenko** [comment] 2019-02-15 17:32
@Motytheultimate yep, that was related to path separator as well, fixed in v 1.0.23 🙂

**Comment by Motytheultimate** [comment] 2019-02-15 18:20
Thank you looks good :)

**Closed** 2019-02-15 18:20 UTC
